[theme]

# Primary accent for interactive elements
primaryColor = '#f0f8ff'

# Background color for the main content area
backgroundColor = '#f0f8ff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#87cefa'

# Color used for almost all text
textColor = '#696969'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"